homework30 was added
Badaev-Aleksandr/AITJavaLessons pull request #10
Opened 2024-05-06 22:12 UTC by Badaev-Aleksandr

2024-05-07 15:05 UTC, zimmermann2013 requested changes

2024-05-07 15:05 UTC, zimmermann2013 commented on src/main/java/homework30/User.java
> +        return videoList;
Опасный возврат оригинального списка

2024-05-07 15:05 UTC, zimmermann2013 commented on src/main/java/homework30/Video.java
> +                ", duration minutes: < " + duration + " m>" +
За оригинальность лайк

2024-05-10 19:18 UTC, Badaev-Aleksandr commented on src/main/java/homework30/User.java
> +        return videoList;
исправленно

2024-05-13 08:23 UTC, zimmermann2013 approved these changes

2024-05-13 08:25 UTC, merged