lesson31 was added
Badaev-Aleksandr/AITJavaLessons pull request #11
Opened 2024-05-12 20:27 UTC by Badaev-Aleksandr

homework31 was added

2024-05-12 20:28 UTC, Badaev-Aleksandr commented
задание 6 постараюсь выполнить завтра

2024-05-12 20:31 UTC, Badaev-Aleksandr commented on src/main/java/homework31/TestsWork.java
> +    //--> В классе тест
Реализованно в тестовом классе

2024-05-12 20:32 UTC, Badaev-Aleksandr commented on src/main/java/homework31/TestsWork.java
> +    // 5. Реализация в классе Student
Реализация в классе Student

2024-05-12 20:33 UTC, Badaev-Aleksandr commented on src/main/java/homework31/TestsWork.java
> +
В процессе

2024-05-13 08:22 UTC, zimmermann2013 requested changes

2024-05-13 08:22 UTC, zimmermann2013 commented on src/main/java/homework31/TestsWork.java
> +
#12

2024-05-13 08:22 UTC, zimmermann2013 commented on src/main/test/homework31/StudentTest.java
> +        students.add(new Student("Sven", 85));
Если эти двое студентов никак не задействованы в тестировании, тогда это возможно избыточные тестовые данные

2024-05-13 08:22 UTC, zimmermann2013 commented on src/main/test/homework31/TestsWorkTest.java
> +        arrayList = new ArrayList<>();
Почему два раза?
Можно в одном инициализировать оба поля

2024-05-13 08:28 UTC, Badaev-Aleksandr commented on src/main/test/homework31/StudentTest.java
> +        students.add(new Student("Sven", 85));
То есть нам в тесте не нужно приводить те данные которые не будут попадать в список? 
То есть только те объекты которые будут в списке прописывать в тестовом классе?

2024-05-13 08:28 UTC, Badaev-Aleksandr commented on src/main/test/homework31/TestsWorkTest.java
> +        arrayList = new ArrayList<>();
Понял исправлю

2024-05-20 13:18 UTC, merged